name: release

on:
  push:
    tags:
      - 'v*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Download language server binaries
        uses: robinraju/release-downloader@v1.4
        with:
          repository: "tensorchord/envd-lsp"
          latest: true
          fileName: "*"
      - name: Package
        run: |
          mkdir -p bin
          mv envd-lsp_* bin/
          chmod a+x bin/*
          npm i
      - name: Package Extension (release)
        run: npx vsce package -o "./vscode-envd.vsix"
      - name: Publish Extension (OpenVSX)
        run: npx ovsx publish --pat ${{ secrets.OPEN_VSX_TOKEN }} --packagePath "./vscode-envd.vsix" --skip-duplicate
        timeout-minutes: 2
      - name: Publish Extension (Code Marketplace)
        run: npx vsce publish --pat ${{ secrets.VS_MARKETPLACE_TOKEN }} --packagePath "./vscode-envd.vsix" --skip-duplicate
        timeout-minutes: 2